# Generated by Django 6.0.6 on 2026-07-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceHistory',
        ),
    ]
