# Generated by Django 6.0.6 on 2026-07-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='devices/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='qr_codes/'),
        ),
    ]
